import { act, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { HelpHint } from './help-hint.js'
import { Dialog, DialogContent, DialogDescription, DialogTitle } from './dialog.js'

afterEach(() => { vi.useRealTimers() })

describe('HelpHint', () => {
  it('hides by default, delays preview and safely crosses the trigger/popup gap', () => {
    vi.useFakeTimers()
    render(<HelpHint label="Language">Full original explanation</HelpHint>)
    const trigger = screen.getByRole('button', { name: 'About Language' })
    expect(screen.queryByRole('tooltip')).toBeNull()
    fireEvent.mouseEnter(trigger)
    act(() => vi.advanceTimersByTime(299))
    expect(screen.queryByRole('tooltip')).toBeNull()
    act(() => vi.advanceTimersByTime(1))
    const popup = screen.getByRole('tooltip')
    expect(trigger.getAttribute('aria-describedby')).toBe(popup.id)
    fireEvent.mouseLeave(trigger)
    act(() => vi.advanceTimersByTime(100))
    fireEvent.mouseEnter(popup)
    act(() => vi.advanceTimersByTime(200))
    expect(screen.getByRole('tooltip')).toBe(popup)
    fireEvent.mouseLeave(popup)
    act(() => vi.advanceTimersByTime(150))
    expect(screen.queryByRole('tooltip')).toBeNull()
  })

  it('pins on click, toggles off, closes outside and allows only one open help', () => {
    vi.useFakeTimers()
    render(<><HelpHint label="First">First explanation</HelpHint><HelpHint label="Second">Second explanation</HelpHint><button>Outside</button></>)
    const first = screen.getByRole('button', { name: 'About First' })
    fireEvent.click(first)
    fireEvent.mouseLeave(first)
    act(() => vi.advanceTimersByTime(1000))
    expect(screen.getByRole('tooltip').textContent).toBe('First explanation')
    fireEvent.click(screen.getByRole('button', { name: 'About Second' }))
    expect(screen.getAllByRole('tooltip')).toHaveLength(1)
    expect(screen.getByRole('tooltip').textContent).toBe('Second explanation')
    fireEvent.pointerDown(screen.getByRole('button', { name: 'Outside' }))
    expect(screen.queryByRole('tooltip')).toBeNull()
    fireEvent.click(first)
    fireEvent.click(first)
    expect(screen.queryByRole('tooltip')).toBeNull()
  })

  it('opens for keyboard focus, dismisses help before its Radix dialog, and does not open on autofocus', () => {
    vi.useFakeTimers()
    const onOpenChange = vi.fn()
    render(<Dialog open onOpenChange={onOpenChange}><DialogContent><DialogTitle>Settings</DialogTitle><DialogDescription>Settings controls</DialogDescription><HelpHint label="Settings">Explanation</HelpHint></DialogContent></Dialog>)
    expect(screen.queryByRole('tooltip')).toBeNull()
    fireEvent.keyDown(document, { key: 'Tab' })
    const trigger = screen.getByRole('button', { name: 'About Settings' })
    act(() => trigger.focus())
    fireEvent.focus(trigger)
    act(() => vi.advanceTimersByTime(50))
    expect(screen.getByRole('tooltip')).toBeTruthy()
    fireEvent.keyDown(document, { key: 'Escape' })
    expect(screen.queryByRole('tooltip')).toBeNull()
    expect(onOpenChange).not.toHaveBeenCalled()
    fireEvent.keyDown(document, { key: 'Escape' })
    expect(onOpenChange).toHaveBeenCalledWith(false)
  })

  it('cleans pending hover and open help on unmount, route, scrolling and resizing', () => {
    vi.useFakeTimers()
    const { unmount } = render(<HelpHint label="Route">Long explanation</HelpHint>)
    const trigger = screen.getByRole('button', { name: 'About Route' })
    for (const event of [new Event('scroll'), new Event('resize'), new PopStateEvent('popstate')]) {
      fireEvent.click(trigger)
      act(() => window.dispatchEvent(event))
      expect(screen.queryByRole('tooltip')).toBeNull()
    }
    fireEvent.mouseEnter(trigger)
    unmount()
    act(() => vi.runAllTimers())
    expect(screen.queryByRole('tooltip')).toBeNull()
  })

  it('attaches passive help to a navigation button without nesting or pinning', () => {
    vi.useFakeTimers()
    const navigate = vi.fn()
    render(<HelpHint label="Interface" trigger={<button onClick={navigate}>Interface</button>}>Original nav hint</HelpHint>)
    const trigger = screen.getByRole('button', { name: 'Interface' })
    expect(document.querySelector('button button')).toBeNull()
    fireEvent.keyDown(document, { key: 'Tab' })
    act(() => trigger.focus())
    act(() => vi.advanceTimersByTime(50))
    expect(screen.getByRole('tooltip').textContent).toBe('Original nav hint')
    fireEvent.click(trigger)
    expect(navigate).toHaveBeenCalledOnce()
    expect(screen.queryByRole('tooltip')).toBeNull()
  })

  it('settles keyboard focus scrolling before showing help, but dismisses subsequent scrolling', () => {
    vi.useFakeTimers()
    render(<div data-testid="scroll-container"><HelpHint label="Offscreen">Full explanation</HelpHint><button>Next</button></div>)
    const trigger = screen.getByRole('button', { name: 'About Offscreen' })
    fireEvent.keyDown(document, { key: 'Tab' })
    act(() => trigger.focus())
    fireEvent.scroll(screen.getByTestId('scroll-container'))
    act(() => vi.advanceTimersByTime(50))
    expect(screen.getByRole('tooltip').textContent).toBe('Full explanation')
    expect(document.activeElement).toBe(trigger)
    fireEvent.scroll(screen.getByTestId('scroll-container'))
    expect(screen.queryByRole('tooltip')).toBeNull()

    act(() => screen.getByRole('button', { name: 'Next' }).focus())
    act(() => trigger.focus())
    act(() => screen.getByRole('button', { name: 'Next' }).focus())
    act(() => vi.advanceTimersByTime(50))
    expect(screen.queryByRole('tooltip')).toBeNull()
  })
})
