import { Pin, X } from 'lucide-react'
import type { SessionSummary } from '@agent-kernel/shared'
import { cn } from '../../lib/utils.js'
import { PREF_HIDE_SUB_AGENT_SESSIONS, useBooleanPref } from '../../lib/prefs.js'

export function SessionTabStrip({sessions,openIds,pinned,active,onSelect,onClose,onPin,onReorder}:{sessions:readonly SessionSummary[];openIds:readonly string[];pinned:readonly string[];active:string|null;onSelect(id:string):void;onClose(id:string):void;onPin(id:string):void;onReorder(from:string,to:string):void}){
 const [hideSubAgentSessions]=useBooleanPref(PREF_HIDE_SUB_AGENT_SESSIONS,true)
 const map=new Map(sessions.map(s=>[s.sessionId,s]));const tabs=openIds.map(id=>map.get(id)).filter((s):s is SessionSummary=>s!==undefined&&(!hideSubAgentSessions||!s.parentSessionId||s.sessionId===active))
 if(!tabs.length)return null
 return <div className="flex h-7 min-w-0 items-stretch gap-px overflow-x-auto rounded-md bg-muted/35 p-px" data-testid="session-tab-strip">{tabs.map((s,i)=>{const isActive=s.sessionId===active;return <button key={s.sessionId} draggable onDragStart={e=>e.dataTransfer.setData('text/session-id',s.sessionId)} onDragOver={e=>e.preventDefault()} onDrop={e=>onReorder(e.dataTransfer.getData('text/session-id'),s.sessionId)} onClick={()=>onSelect(s.sessionId)} onAuxClick={e=>{if(e.button===1)onClose(s.sessionId)}} className={cn('group flex min-w-[9rem] max-w-[14rem] items-center gap-2 rounded px-3 text-xs',isActive?'bg-background text-foreground':'text-muted-foreground hover:bg-accent/60')} title={`${i<9?`${navigator.platform.includes('Mac')?'⌘':'Ctrl'}+${i+1} · `:''}${s.label||s.firstUserMessage||s.sessionId}`}><span className={cn('h-2 w-2 rounded-full',s.status==='thinking'||s.status==='executing_tools'?'bg-blue-500':s.status==='awaiting_approval'?'bg-amber-500':s.status==='error'?'bg-rose-500':'bg-muted-foreground/35')}/><span className="min-w-0 flex-1 truncate">{s.label||s.firstUserMessage||'Untitled session'}</span>{pinned.includes(s.sessionId)?<Pin className="h-3 w-3" onClick={e=>{e.stopPropagation();onPin(s.sessionId)}}/>:<Pin className="hidden h-3 w-3 group-hover:block" onClick={e=>{e.stopPropagation();onPin(s.sessionId)}}/>}<X className="h-3 w-3 opacity-50 hover:opacity-100" onClick={e=>{e.stopPropagation();onClose(s.sessionId)}}/></button>})}</div>
}
