import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const root = new URL('../../', import.meta.url)
const read = async (path) => await readFile(new URL(path, root), 'utf8')

test('slot service shares one logical state root and one write lease', async () => {
  const unit = await read('deploy/dedicated-systemd/agent-runlab-dedicated-unit@.service')
  assert.match(unit, /units\/local\/write\.lock/)
  assert.match(unit, /\.agent-kernel\/sessions/)
  assert.match(unit, /EnvironmentFile=\/etc\/agent-runlab\/slots\/%i\.env/)
  assert.match(unit, /Restart=on-failure/)
  assert.match(unit, /RuntimeDirectory=agent-runlab/)
  assert.match(unit, /RuntimeDirectoryPreserve=yes/)
  assert.match(unit, /ExecStopPost=\/usr\/bin\/rm -f \/run\/agent-runlab\/unit-%i-readiness\.json \/run\/agent-runlab\/unit-%i-process-ready\.json/)
})

test('Ingress reads one persistent route authority and Supervisor transfers boot ownership', async () => {
  const ingress = await read('deploy/dedicated-systemd/agent-runlab-dedicated-ingress.service')
  const supervisorService = await read('deploy/dedicated-systemd/agent-runlab-dedicated-deploy-supervisor.service')
  const supervisor = await read('packages/host/bin/agent-runlab-dedicated-deploy-supervisor.ts')
  assert.match(ingress, /AGENT_RUNLAB_ROUTE_STATE=\/var\/lib\/agent-runlab\/deploy\/route-state\.json/)
  assert.match(ingress, /AGENT_RUNLAB_DASHBOARD_STATE=\/var\/lib\/agent-runlab\/deploy\/dashboard\/route-state\.json/)
  assert.doesNotMatch(supervisor, /active-route\.json/)
  assert.match(supervisor, /systemctl\('enable', '--now', unitService\(slot\)\)/)
  assert.match(supervisor, /systemctl\('disable', '--now', unitService\(slot\)\)/)
  assert.ok(supervisor.includes("readFile('/proc/locks'"))
  assert.ok(!supervisor.includes('/proc/${pid}/fd'))
  assert.match(supervisorService, /flock --exclusive --nonblock --no-fork/)
  assert.match(ingress, /RuntimeDirectory=agent-runlab/)
  assert.match(ingress, /RuntimeDirectoryPreserve=yes/)
})

test('control-plane updates use a separately supervised durable state machine', async () => {
  const updater = await read('scripts/deploy/update-dedicated-control-plane.mjs')
  const service = await read('deploy/dedicated-systemd/agent-runlab-dedicated-control-updater.service')
  assert.match(updater, /const transitions =/)
  assert.ok(updater.includes("requested: new Set(['activating'"))
  assert.ok(updater.includes("rolling_back: new Set(['rolled_back', 'rollback_failed'])"))
  assert.ok(updater.includes("await systemctl('restart', 'agent-runlab-dedicated-ingress.service')"))
  assert.ok(updater.includes("await systemctl('restart', 'agent-runlab-dedicated-deploy-supervisor.service')"))
  assert.match(service, /Type=oneshot/)
  assert.match(service, /Restart=on-failure/)
  assert.ok(service.includes('control-updater-current/update-dedicated-control-plane.mjs'))
  assert.ok(service.includes('AGENT_RUNLAB_OPERATOR_STATUS=/var/lib/agent-runlab/deploy/operator-status.json'))
  assert.ok(service.includes('ReadOnlyPaths=-/run/agent-runlab/ingress-readiness.json'))
})

test('installer fails closed on old Node and records explicit container backend policy', async () => {
  const installer = await read('scripts/deploy/install-dedicated-systemd.mjs')
  assert.match(installer, /Node\.js 22\+ is required/)
  assert.match(installer, /AGENT_RUNLAB_CONTAINER_BACKEND/)
  assert.match(installer, /containerBackend/)
  assert.match(installer, /runuser.*agent-runlab.*docker.*info/s)
  assert.match(installer, /AGENT_RUNLAB_INGRESS_HANDOFF_SECRET/)
  assert.match(installer, /randomBytes\(32\)\.toString\('base64url'\)/)
  assert.match(installer, /open\(path, 'wx', 0o600\)/)
  const cutover = await read('scripts/deploy/cutover-dedicated-systemd.mjs')
  const migration = await read('scripts/deploy/dedicated-data-migration.mjs')
  assert.match(cutover, /sanitised provider\/model settings fingerprint changed during migration/)
  assert.match(cutover, /executeDedicatedDataMigration/)
  assert.match(cutover, /probeDedicatedAtomicRename/)
  assert.match(cutover, /rollbackDedicatedData/)
  assert.match(cutover, /data_migration_planned/)
  assert.match(cutover, /rollback_data_restored/)
  assert.match(cutover, /writeAtomicJson/)
  assert.match(migration, /\.claude\/settings\.json/)
  assert.match(migration, /\.codex\/config\.toml/)
  assert.match(migration, /\.codex\/auth\.json/)
  assert.match(migration, /\.config\/agent-kernel\/models\.json/)
  const finalizer = await read('deploy/dedicated-systemd/agent-runlab-dedicated-migration-finalizer.service')
  assert.match(finalizer, /Type=oneshot/)
  assert.match(finalizer, /TimeoutStartSec=0/)
  assert.match(finalizer, /Restart=on-failure/)
  assert.match(finalizer, /StartLimitBurst=3/)
  assert.match(finalizer, /cutover-dedicated-systemd\.mjs/)
  assert.doesNotMatch(finalizer, /\/home\/ubuntu/)
  assert.doesNotMatch(finalizer, /ReadWritePaths=\/var\/lib\/agent-runlab/)
  assert.match(finalizer, /ProtectSystem=full/)
  assert.doesNotMatch(installer, /10-legacy-data\.conf/)
  assert.match(installer, /assertStagedServicesDisabled/)
})
