import { readFileSync } from 'node:fs'

const rootRead = (relative) => readFileSync(new URL(`../../${relative}`, import.meta.url), 'utf8')
import { describe, expect, it } from 'vitest'

const read = (name) => readFileSync(new URL(`../../deploy/dedicated-systemd/${name}`, import.meta.url), 'utf8')

describe('Dedicated systemd packaging', () => {
  it('keeps Ingress, Unit, and Supervisor in independent services', () => {
    const ingress = read('agent-runlab-dedicated-ingress.service')
    const unit = read('agent-runlab-dedicated-unit@.service')
    const supervisor = read('agent-runlab-dedicated-deploy-supervisor.service')
    const updater = read('agent-runlab-dedicated-control-updater.service')
    expect(ingress).toContain('agent-runlab-dedicated-ingress.cjs')
    expect(unit).toContain('agent-runlab-runtime.cjs --port ${HOST_PORT}')
    expect(unit).not.toContain('bundle-dashboard-with-runtime.cjs')
    expect(unit).toContain('/usr/bin/flock --exclusive --nonblock --no-fork')
    expect(unit).toContain('Restart=on-failure')
    expect(unit).toContain('AGENT_RUNLAB_RUNTIME_READINESS=/run/agent-runlab/unit-%i-readiness.json')
    expect(unit).toContain('AGENT_RUNLAB_PROCESS_READINESS=/run/agent-runlab/unit-%i-process-ready.json')
    expect(unit).toContain('ExecStopPost=/usr/bin/rm -f /run/agent-runlab/unit-%i-readiness.json /run/agent-runlab/unit-%i-process-ready.json')
    expect(unit).toContain('AGENT_RUNLAB_WRITE_LEASE=/var/lib/agent-runlab/units/local/write.lock')
    expect(unit).toContain('COPILOT_CLI_PATH=/var/lib/agent-runlab/deploy/slots/%i/copilot-cli')
    expect(unit).toContain('/var/lib/agent-runlab/deploy/requests')
    expect(unit).toContain('/var/lib/agent-runlab/deploy/submissions')
    expect(supervisor).toContain('deploy/control-current/agent-runlab-dedicated-deploy-supervisor.cjs')
    expect(supervisor).toContain('/usr/bin/flock --exclusive --nonblock --no-fork')
    expect(supervisor).toContain('ReadOnlyPaths=/var/lib/agent-runlab/admission /var/lib/agent-runlab/units/local/write.lock')
    expect(supervisor).not.toContain('CAP_SYS_PTRACE')
    expect(supervisor).toContain('ReadOnlyPaths=/var/lib/agent-runlab/admission')
    expect(supervisor).not.toContain('agent-runlab-runtime.cjs')
    expect(updater).toContain('deploy/control-updater-current/update-dedicated-control-plane.mjs')
    expect(updater).toContain('AGENT_RUNLAB_INGRESS_READINESS=/run/agent-runlab/ingress-readiness.json')
    expect(updater).toContain('Type=oneshot')
    expect(updater).toContain('Restart=on-failure')
    expect(ingress).toContain('AGENT_RUNLAB_OPERATOR_STATUS=/var/lib/agent-runlab/deploy/operator-status.json')
    expect(ingress).toContain('AGENT_RUNLAB_DASHBOARD_STATE=/var/lib/agent-runlab/deploy/dashboard/route-state.json')
    expect(ingress).toContain('AGENT_RUNLAB_DASHBOARD_RELEASES=/var/lib/agent-runlab/deploy/dashboard/releases')
    expect(ingress).toContain('AGENT_RUNLAB_INGRESS_READINESS=/run/agent-runlab/ingress-readiness.json')
    expect(ingress).toContain('AGENT_RUNLAB_ADMISSION_LEDGER=/var/lib/agent-runlab/admission/ledger.json')
    for (const service of [ingress, unit]) {
      expect(service).toContain('RuntimeDirectory=agent-runlab')
      expect(service).toContain('RuntimeDirectoryPreserve=yes')
    }
  })

  it('binds the Unit privately and preserves full Dedicated profile', () => {
    const unit = read('agent-runlab-dedicated-unit@.service')
    expect(unit).toContain('AGENT_RUNLAB_DEPLOYMENT_CONFIG=/etc/agent-runlab/deployment.json')
    expect(unit).toContain('HOST_LISTEN_HOST=127.0.0.1')
    expect(unit).toContain('SESSIONS_DIR=/var/lib/agent-runlab/.agent-kernel/sessions')
    expect(unit).toContain('EnvironmentFile=/etc/agent-runlab/slots/%i.env')
  })

  it('uses real blue and green systemd instances throughout cutover and rollback', () => {
    const cutover = rootRead('scripts/deploy/cutover-dedicated-systemd.mjs')
    const rollback = rootRead('scripts/deploy/rollback-dedicated-systemd.mjs')
    const architecture = rootRead('docs/architecture/dedicated-platform-runtime-unit.md')
    for (const source of [cutover, rollback, architecture]) {
      expect(source).not.toMatch(/user[23]@example\.com/)
    }
    expect(cutover).toContain("agent-runlab-dedicated-unit@blue.service")
    expect(rollback).toContain("agent-runlab-dedicated-unit@blue.service")
    expect(rollback).toContain("agent-runlab-dedicated-unit@green.service")
    expect(rollback).toContain("const enabledServices =")
    expect(rollback).toContain("await systemctl('disable', service)")
    expect(cutover).toContain("'data_migration_planned'")
    expect(cutover).toContain("'rollback_data_restored'")
    expect(cutover).toContain('writeAtomicJson(receiptPath')
  })

  it('packages the standard Supervisor deployment client', () => {
    const packageJson = JSON.parse(rootRead('package.json'))
    const builder = rootRead('scripts/release/build-release-assets.mjs')
    const installer = rootRead('scripts/deploy/install-dedicated-systemd.mjs')
    expect(packageJson.scripts['deploy:dedicated']).toContain('deploy-dedicated.mjs')
    expect(builder).toContain('scripts/deploy/deploy-dedicated.mjs')
    expect(builder).toContain('scripts/deploy/runlab-dedicated.mjs')
    expect(installer).toContain('deploy-dedicated.mjs')
    expect(installer).toContain('runlab-dedicated.mjs')
    expect(installer).toContain('dedicated-settings-fingerprint.mjs')
    expect(builder).toContain('deploy/dedicated-systemd/deployment.json')
    expect(installer).toContain("copyFile(join(source, 'deployment.json'), '/etc/agent-runlab/deployment.json')")
    expect(installer).toContain("const path = '/etc/agent-runlab/handoff.env'")
    expect(installer).toContain("randomBytes(32).toString('base64url')")
    expect(installer).toContain("open(path, 'wx', 0o600)")
    expect(installer).toContain('existing Dedicated handoff secret file is invalid')
    expect(installer).toContain("type === 'd' && (listed === '.' || listed === './')")
    expect(installer).toContain("join(dataRoot, 'deploy', 'dashboard', 'route-state.json')")
    expect(installer).toContain("join(dataRoot, 'deploy', 'dashboard', 'releases'), join(dataRoot, 'deploy', 'dashboard', 'route-state.json')")
    expect(installer).toContain("chmod', ['750', join(dataRoot, 'deploy', 'dashboard'), join(dataRoot, 'deploy', 'dashboard', 'releases')")
    expect(installer).toContain('await sealDashboardTree(incoming)')
    expect(installer).toContain('await chmod(root, 0o555)')
    expect(installer).toContain("...manifest.assets, 'manifest.json', 'SHA256SUMS', 'RELEASE_NOTES.md'")
    expect(installer).toContain("'3770', join(dataRoot, 'deploy', 'requests'), join(dataRoot, 'deploy', 'submissions')")
    expect(installer).toContain("if (!legacyDataRoot) await mkdir(join(dataRoot, '.agent-kernel'), { recursive: true, mode: 0o700 })")
    expect(installer).toContain("...(legacyDataRoot ? [] : [join(dataRoot, '.agent-kernel')])")
    expect(installer).toContain('assertStagedServicesDisabled()')
    expect(installer).toContain("agent-runlab-dedicated-control-updater.service")
    expect(installer).toContain("join(dataRoot, 'deploy', 'control-current')")
    expect(installer).toContain("'disabled', 'static', 'indirect', 'masked', 'not-found', 'generated', 'transient'")
    expect(installer).toContain("'enabled', 'enabled-runtime', 'linked', 'linked-runtime', 'alias'")
    expect(installer).not.toContain("['is-enabled', '--quiet', service]")
    expect(installer).not.toContain('10-legacy-data.conf')
    expect(installer).toContain('releaseDigest:')
    expect(builder).toContain('__AGENT_KERNEL_EMBEDDED_DOCS__')
    expect(builder).toContain('embeddedDocsBanner(docsDir)')
  })

})
