import { readFileSync } from 'node:fs'

const rootRead = (relative) => readFileSync(new URL(`../../${relative}`, import.meta.url), 'utf8')
import { describe, expect, it } from 'vitest'

const read = (name) => readFileSync(new URL(`../../deploy/dedicated-systemd/${name}`, import.meta.url), 'utf8')

describe('Dedicated systemd packaging', () => {
  it('keeps Ingress, Unit, and Supervisor in independent services', () => {
    const ingress = read('kala-dedicated-ingress.service')
    const unit = read('kala-dedicated-unit@.service')
    const supervisor = read('kala-dedicated-deploy-supervisor.service')
    const updater = read('kala-dedicated-control-updater.service')
    expect(ingress).toContain('kala-dedicated-ingress.cjs')
    expect(unit).toContain('kala-runtime.cjs --port ${KALA_PORT}')
    expect(unit).not.toContain('kala-dashboard-with-runtime.cjs')
    expect(unit).toContain('/usr/bin/flock --exclusive --nonblock --no-fork')
    expect(unit).toContain('Restart=on-failure')
    expect(unit).toContain('KALA_RUNTIME_READINESS=/run/kala/unit-%i-readiness.json')
    expect(unit).toContain('KALA_PROCESS_READINESS=/run/kala/unit-%i-process-ready.json')
    expect(unit).toContain('ExecStopPost=/usr/bin/rm -f /run/kala/unit-%i-readiness.json /run/kala/unit-%i-process-ready.json')
    expect(unit).toContain('KALA_WRITE_LEASE=/var/lib/kala/units/local/write.lock')
    expect(unit).toContain('KALA_ROUTE_STATE=/var/lib/kala/deploy/route-state.json')
    expect(unit).toContain('/var/lib/kala/deploy/requests')
    expect(unit).toContain('/var/lib/kala/deploy/submissions')
    expect(unit).toContain('/var/lib/kala/.config/kala')
    expect(supervisor).toContain('deploy/control-current/kala-dedicated-deploy-supervisor.cjs')
    expect(supervisor).toContain('/usr/bin/flock --exclusive --nonblock --no-fork')
    expect(supervisor).toContain('ReadOnlyPaths=/var/lib/kala/admission /var/lib/kala/units/local/write.lock')
    expect(supervisor).not.toContain('CAP_SYS_PTRACE')
    expect(supervisor).toContain('ReadOnlyPaths=/var/lib/kala/admission')
    expect(supervisor).not.toContain('kala-runtime.cjs')
    expect(updater).toContain('deploy/control-updater-current/update-dedicated-control-plane.mjs')
    expect(updater).toContain('KALA_INGRESS_READINESS=/run/kala/ingress-readiness.json')
    expect(updater).toContain('Type=oneshot')
    expect(updater).toContain('Restart=on-failure')
    expect(ingress).toContain('KALA_OPERATOR_STATUS=/var/lib/kala/deploy/operator-status.json')
    expect(ingress).toContain('KALA_DASHBOARD_STATE=/var/lib/kala/deploy/dashboard/route-state.json')
    expect(ingress).toContain('KALA_DASHBOARD_RELEASES=/var/lib/kala/deploy/dashboard/releases')
    expect(ingress).toContain('KALA_INGRESS_READINESS=/run/kala/ingress-readiness.json')
    expect(ingress).toContain('KALA_ADMISSION_LEDGER=/var/lib/kala/admission/ledger.json')
    for (const service of [ingress, unit]) {
      expect(service).toContain('RuntimeDirectory=kala')
      expect(service).toContain('RuntimeDirectoryPreserve=yes')
    }
  })

  it('binds the Unit privately and preserves full Dedicated profile', () => {
    const unit = read('kala-dedicated-unit@.service')
    expect(unit).toContain('KALA_DEPLOYMENT_CONFIG=/etc/kala/deployment.json')
    expect(unit).toContain('KALA_BIND_HOST=127.0.0.1')
    expect(unit).toContain('KALA_SESSIONS_DIR=/var/lib/kala/.kala/sessions')
    expect(unit).toContain('EnvironmentFile=/etc/kala/slots/%i.env')
  })

  it('uses real blue and green systemd instances throughout cutover and rollback', () => {
    const cutover = rootRead('scripts/deploy/cutover-dedicated-systemd.mjs')
    const rollback = rootRead('scripts/deploy/rollback-dedicated-systemd.mjs')
    const architecture = rootRead('docs/architecture/dedicated-platform-runtime-unit.md')
    for (const source of [cutover, rollback, architecture]) {
      expect(source).not.toMatch(/user[23]@example\.com/)
    }
    expect(cutover).toContain("kala-dedicated-unit@blue.service")
    expect(rollback).toContain("kala-dedicated-unit@blue.service")
    expect(rollback).toContain("kala-dedicated-unit@green.service")
    expect(rollback).toContain("const enabledServices =")
    expect(rollback).toContain("await systemctl('disable', service)")
    expect(cutover).toContain("'data_migration_planned'")
    expect(cutover).toContain("'rollback_data_restored'")
    expect(cutover).toContain('writeAtomicJson(receiptPath')
  })

  it('packages the standard Supervisor deployment client', () => {
    const packageJson = JSON.parse(rootRead('package.json'))
    const builder = rootRead('scripts/release/build-release-assets.mjs')
    const supportBuilder = rootRead('scripts/release/dedicated-support-bundle.mjs')
    const installer = rootRead('scripts/deploy/install-dedicated-systemd.mjs')
    expect(packageJson.scripts['deploy:dedicated']).toContain('deploy-dedicated.mjs')
    expect(supportBuilder).toContain('scripts/deploy/deploy-dedicated.mjs')
    expect(builder).toContain('scripts/deploy/kala-dedicated.mjs')
    expect(installer).toContain('deploy-dedicated.mjs')
    expect(installer).toContain('kala-dedicated.mjs')
    expect(installer).toContain('dedicated-settings-fingerprint.mjs')
    expect(supportBuilder).toContain('deploy/dedicated-systemd/deployment.json')
    expect(installer).toContain("copyFile(join(source, 'deployment.json'), '/etc/kala/deployment.json')")
    expect(installer).toContain("const path = '/etc/kala/handoff.env'")
    expect(installer).toContain("randomBytes(32).toString('base64url')")
    expect(installer).toContain("open(path, 'wx', 0o600)")
    expect(installer).toContain('existing Dedicated handoff secret file is invalid')
    expect(installer).toContain("archive contains a non-regular entry")
    expect(installer).toContain("join(dataRoot, 'deploy', 'dashboard', 'route-state.json')")
    expect(installer).toContain("join(dataRoot, 'deploy', 'dashboard', 'releases'), join(dataRoot, 'deploy', 'dashboard', 'route-state.json')")
    expect(installer).toContain("chmod', ['750', join(dataRoot, 'deploy', 'dashboard'), join(dataRoot, 'deploy', 'dashboard', 'releases')")
    expect(installer).toContain('await sealDashboardTree(incoming)')
    expect(installer).toContain('await chmod(root, 0o555)')
    expect(installer).toContain("...manifest.assets, 'manifest.json', 'SHA256SUMS', ...signature")
    expect(installer).toContain("join(sourceRoot, 'kala-dashboard.tar.gz')")
    expect(installer).not.toContain("join(sourceRoot, 'kala-dashboard-dist.tar.gz')")
    expect(installer).toContain("'3770', join(dataRoot, 'deploy', 'requests'), join(dataRoot, 'deploy', 'submissions')")
    expect(installer).toContain("if (!legacyDataRoot) await mkdir(join(dataRoot, '.kala'), { recursive: true, mode: 0o700 })")
    expect(installer).toContain("...(legacyDataRoot ? [] : [join(dataRoot, '.kala')])")
    expect(installer).toContain('assertStagedServicesDisabled()')
    expect(installer).toContain("kala-dedicated-control-updater.service")
    expect(installer).toContain("join(dataRoot, 'deploy', 'control-current')")
    expect(installer).toContain("'disabled', 'static', 'indirect', 'masked', 'not-found', 'generated', 'transient'")
    expect(installer).toContain("'enabled', 'enabled-runtime', 'linked', 'linked-runtime', 'alias'")
    expect(installer).not.toContain("['is-enabled', '--quiet', service]")
    expect(installer).not.toContain('10-legacy-data.conf')
    expect(installer).toContain('releaseDigest:')
    expect(builder).toContain('__KALA_EMBEDDED_DOCS__')
    expect(builder).toContain('embeddedDocsBanner(docsDir)')
  })

})
