import { useEffect, useState } from 'react'
import { Button } from '../../components/ui/button.js'
import { ProductState } from '../../components/ui/product-state.js'

type Row = Record<string, any>
export type OrganizationSnapshot = { organization: Row; role:'owner'|'admin'|'member'|'viewer'; permissions:string[]; members:Array<Row>; entitlement?:Row; retention?:Row; usage?:Row; workspaces:Array<Row>; executorPools:Array<Row>; executors:Array<Row>; invites:Array<Row>; browserSessions:Array<Row>; serviceAccounts:Array<Row>; webhooks:Array<Row>; audit:Array<Row>; integrations:Row }
const tabs=['Overview','Members','Workspaces','Executors','Policies','Usage & security','Integrations'] as const
async function mutate(path:string,method:string,body?:unknown){const response=await fetch(path,{method,headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(!response.ok)throw new Error(`${method} ${path}: ${response.status}`)}
export function AdminCenter({onClose}:{onClose():void}):JSX.Element{
 const [snapshot,setSnapshot]=useState<OrganizationSnapshot|null>(null),[error,setError]=useState<string|null>(null),[tab,setTab]=useState<(typeof tabs)[number]>('Overview')
 const load=async()=>{setError(null);try{const response=await fetch('/organization',{cache:'no-store'});if(!response.ok)throw new Error('Organization administration is unavailable.');setSnapshot(await response.json())}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}}
 useEffect(()=>{void load()},[])
 const canManage=snapshot?.permissions.includes('organization:manage')??false, canPolicy=snapshot?.permissions.includes('policy:manage')??false
 return <div className="fixed inset-0 z-[71] overflow-y-auto bg-background" data-testid="admin-center"><header className="sticky top-0 z-10 flex min-h-14 items-center justify-between border-b bg-background/95 px-4"><div><h1 className="font-semibold">Organization administration</h1><p className="text-xs text-muted-foreground">Members, workspaces, executors, policy, usage, and security</p></div><Button variant="ghost" onClick={onClose}>Close</Button></header>
 <main className="mx-auto max-w-6xl p-4 md:p-6">{error?<ProductState kind="forbidden" title="Administration unavailable" description={error} primary={{label:'Retry',onClick:()=>void load()}}/>:!snapshot?<ProductState kind="loading" title="Loading organization" description="Resolving administration data."/>:<><nav className="mb-5 flex gap-1 overflow-x-auto">{tabs.map(x=><Button key={x} size="sm" variant={tab===x?'outline':'ghost'} onClick={()=>setTab(x)}>{x}</Button>)}</nav>
 {tab==='Overview'?<Grid><Card title={snapshot.organization.name}><KV rows={{Status:snapshot.organization.status,Role:snapshot.role,'Runtime unit':snapshot.organization.runtime_unit_id}}/></Card><Card title="Contract"><KV rows={{Reference:snapshot.entitlement?.contract_reference,Tier:snapshot.entitlement?.support_tier,Ends:snapshot.entitlement?.ends_at,Seats:snapshot.entitlement?.seat_limit,'Concurrent sessions':snapshot.entitlement?.concurrent_session_limit,'Monthly token limit':snapshot.entitlement?.monthly_token_limit??'Unlimited'}}/></Card><Card title="Current month"><KV rows={{Tokens:snapshot.usage?.tokens??0,Sessions:snapshot.usage?.sessions??0,'Ledger entries':snapshot.usage?.entries??0}}/></Card></Grid>:null}
 {tab==='Members'?<Card title="Members" action={canManage?<Button size="sm" onClick={()=>void addMember(snapshot,load,setError)}>Add member</Button>:undefined}>{snapshot.members.map(m=><Line key={`${m.issuer}:${m.subject}`} title={m.displayName||m.email||m.subject} subtitle={m.email||m.subject} right={<div className="flex gap-2"><select disabled={!canManage||m.role==='owner'} value={m.role} onChange={e=>void mutate('/organization/members','PATCH',{issuer:m.issuer,subject:m.subject,role:e.target.value}).then(load).catch(e=>setError(String(e)))} className="rounded border bg-background px-2"><option>admin</option><option>member</option><option>viewer</option><option>owner</option></select>{canManage&&m.role!=='owner'?<Button size="sm" variant="destructive" onClick={()=>void mutate('/organization/members','DELETE',{issuer:m.issuer,subject:m.subject}).then(load)}>Remove</Button>:null}</div>}/>)}</Card>:null}
 {tab==='Workspaces'?<Grid><Card title="Workspaces">{snapshot.workspaces.length?snapshot.workspaces.map(w=><Line key={w.id} title={w.name} subtitle={`${w.status} · policy v${w.policy_version}`}/>):<Empty text="No registered workspaces. Add one from Agent."/>}</Card><Card title="Executor pool bindings">{snapshot.executorPools.map(p=><Line key={p.id} title={p.name} subtitle={`${p.mode}${p.workspace_id?` · ${p.workspace_id}`:''}`}/>)}</Card></Grid>:null}
 {tab==='Executors'?<Grid><Card title="Executors">{snapshot.executors.length?snapshot.executors.map(e=><Line key={e.id} title={e.name} subtitle={`${e.status} · last seen ${e.last_seen_at||'never'}`}/>):<Empty text="No enrolled executors."/>}</Card><Card title="Pending invites">{snapshot.invites.length?snapshot.invites.map(i=><Line key={i.id} title={i.email_normalized} subtitle={`${i.role} · expires ${i.expires_at}`}/>):<Empty text="No pending organization invites."/>}</Card></Grid>:null}
 {tab==='Policies'?<Card title="Retention policy" action={canPolicy?<Button size="sm" onClick={()=>void editRetention(snapshot,load,setError)}>Edit</Button>:undefined}><KV rows={{'Session days':snapshot.retention?.session_days,'Artifact days':snapshot.retention?.artifact_days,'Audit days':snapshot.retention?.audit_days,'Deleted resource grace':snapshot.retention?.deleted_resource_grace_days,Version:snapshot.retention?.version}}/></Card>:null}
 {tab==='Usage & security'?<Grid><Card title="Browser sessions">{snapshot.browserSessions.map(s=><Line key={s.id} title={s.device?.browser||'Browser'} subtitle={`Last active ${s.last_seen_at}${s.revoked_at?' · revoked':''}`}/>)}</Card><Card title="Service accounts">{snapshot.serviceAccounts.length?snapshot.serviceAccounts.map(s=><Line key={s.id} title={s.display_name||s.email||s.id} subtitle={(s.scopes||[]).join(', ')}/>):<Empty text="No service account tokens."/>}</Card><Card title="Webhooks">{snapshot.webhooks.length?snapshot.webhooks.map(w=><Line key={w.id} title={w.url} subtitle={`${w.enabled?'enabled':'disabled'} · ${(w.topics||[]).join(', ')}`}/>):<Empty text="No webhook endpoints."/>}</Card><Card title="Audit log">{snapshot.audit.length?snapshot.audit.map(a=><Line key={a.id} title={a.action} subtitle={`${a.result} · ${a.occurred_at}`}/>):<Empty text="No audit events."/>}</Card></Grid>:null}
 {tab==='Integrations'?<Card title="Deployment adapters"><KV rows={{Secrets:snapshot.integrations?.secrets,Artifacts:snapshot.integrations?.artifacts,Telemetry:snapshot.integrations?.telemetry?'Connected':'Not configured','Error reporting':snapshot.integrations?.errorReporting?'Connected':'Not configured',Ticketing:snapshot.integrations?.ticketing?'Connected':'Not configured'}}/><p className="mt-3 text-xs text-muted-foreground">Only configured adapters are reported as connected.</p></Card>:null}</>}</main></div>
}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-5 md:grid-cols-2">{children}</div>}function Card({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode}){return <section className="rounded-xl border bg-card/70 p-5"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">{title}</h2>{action}</div>{children}</section>}function Line({title,subtitle,right}:{title:string;subtitle?:string;right?:React.ReactNode}){return <div className="flex items-center justify-between gap-3 border-t py-3 first:border-0"><div className="min-w-0"><div className="truncate text-sm font-medium">{title}</div>{subtitle?<div className="truncate text-xs text-muted-foreground">{subtitle}</div>:null}</div>{right}</div>}function KV({rows}:{rows:Record<string,unknown>}){return <dl className="grid gap-2 text-sm">{Object.entries(rows).map(([k,v])=><div key={k} className="flex justify-between gap-4"><dt className="text-muted-foreground">{k}</dt><dd className="text-right">{String(v??'—')}</dd></div>)}</dl>}function Empty({text}:{text:string}){return <p className="text-sm text-muted-foreground">{text}</p>}
async function addMember(s:OrganizationSnapshot,reload:()=>Promise<void>,fail:(v:string)=>void){const issuer=prompt('OIDC issuer'),subject=prompt('OIDC subject'),email=prompt('Email'),role=prompt('Role: admin, member, viewer','member');if(!issuer||!subject||!role)return;try{await mutate('/organization/members','POST',{issuer,subject,email,role});await reload()}catch(e){fail(String(e))}}
async function editRetention(s:OrganizationSnapshot,reload:()=>Promise<void>,fail:(v:string)=>void){const n=(label:string,key:string)=>Number(prompt(label,String(s.retention?.[key]??30)));try{await mutate('/organization/retention','PUT',{sessionDays:n('Session days','session_days'),artifactDays:n('Artifact days','artifact_days'),auditDays:n('Audit days','audit_days'),deletedResourceGraceDays:n('Deleted resource grace days','deleted_resource_grace_days')});await reload()}catch(e){fail(String(e))}}
