import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import type { SessionSummary, SubAgentListResult } from '@agent-kernel/shared'
import { DesktopSubagentClassifier } from './desktop-subagents.js'

const child = (sessionId: string, parentSessionId = 'parent'): SessionSummary => ({ sessionId, parentSessionId, agentRuntime: 'kernel', createdAt: '2026-09-15', status: 'thinking', eventCount: 1 })
const result = (parentSessionId: string, children: SubAgentListResult['children'] = [], error?: string): SubAgentListResult => ({ requestId: 'test', parentSessionId, children, ...(error ? { error } : {}) })

describe('bounded native subagent classification', () => {
  beforeEach(() => vi.useFakeTimers())
  afterEach(() => vi.useRealTimers())
  it('quarantines unresolved children, reports server errors, retries and distinguishes forks on success', async () => {
    const query = vi.fn().mockResolvedValueOnce(result('parent', [], 'server unavailable'))
      .mockResolvedValueOnce(result('parent', [{ childSessionId: 'tool', status: 'running', startedAt: '2026-09-15' }, { childSessionId: 'fork', status: 'running' }]))
    const error = vi.fn()
    const classifier = new DesktopSubagentClassifier(query, vi.fn(), error)
    classifier.update([child('tool'), child('fork')])
    expect([...classifier.snapshot.unresolved]).toEqual(['fork', 'tool'])
    await vi.advanceTimersByTimeAsync(0)
    expect(error).toHaveBeenCalledOnce()
    expect(classifier.snapshot.unresolved.size).toBe(2)
    await vi.advanceTimersByTimeAsync(500)
    expect(query).toHaveBeenCalledTimes(2)
    expect([...classifier.snapshot.subagents]).toEqual(['tool'])
    expect(classifier.snapshot.unresolved.size).toBe(0)
    classifier.update([child('fork'), child('tool')])
    await vi.advanceTimersByTimeAsync(10_000)
    expect(query).toHaveBeenCalledTimes(2)
    classifier.dispose()
  })
  it('stops after three failures rather than refetching on every rerender', async () => {
    const query = vi.fn().mockResolvedValue(result('parent', [], 'still unavailable'))
    const classifier = new DesktopSubagentClassifier(query, vi.fn(), vi.fn())
    classifier.update([child('fork')])
    await vi.advanceTimersByTimeAsync(20_000)
    for (let index = 0; index < 50; index++) classifier.update([child('fork')])
    await vi.advanceTimersByTimeAsync(20_000)
    expect(query).toHaveBeenCalledTimes(3)
    expect(classifier.snapshot.failedParents).toEqual(['parent'])
    expect(classifier.snapshot.unresolved.has('fork')).toBe(true)
    classifier.dispose()
  })
  it('caps concurrency at four and fences stale results across snapshot changes and reconnect', async () => {
    const pending: Array<{ parent: string; resolve(value: SubAgentListResult): void }> = []
    const query = vi.fn((parent: string) => new Promise<SubAgentListResult>((resolve) => pending.push({ parent, resolve })))
    const classifier = new DesktopSubagentClassifier(query, vi.fn(), vi.fn())
    const sessions = Array.from({ length: 10 }, (_, index) => child(`c${index}`, `p${index}`))
    classifier.update(sessions)
    await vi.advanceTimersByTimeAsync(0)
    expect(query).toHaveBeenCalledTimes(4)
    classifier.reset()
    classifier.update([child('new', 'fresh')])
    for (const item of pending.splice(0)) item.resolve(result(item.parent, [{ childSessionId: 'new', parentCallId: 'stale', status: 'running' }]))
    await vi.advanceTimersByTimeAsync(0)
    expect(classifier.snapshot.subagents.size).toBe(0)
    expect(query).toHaveBeenCalledTimes(5)
    pending[0]!.resolve(result('fresh', [{ childSessionId: 'new', status: 'running' }]))
    await vi.advanceTimersByTimeAsync(0)
    expect(classifier.snapshot.unresolved.size).toBe(0)
    expect(classifier.snapshot.subagents.size).toBe(0)
    classifier.dispose()
  })
})
