/**
 * PWA registration + update prompt.
 *
 * vite-plugin-pwa exposes `virtual:pwa-register` — a tiny wrapper around
 * workbox-window that reports when a new SW is waiting and when the app is
 * ready to run offline. We drive both signals through explicit callbacks
 * so the surrounding UI (BannerStack) decides how to present them.
 *
 * Rules the callbacks encode (see docs/planning/roadmap-notes/pwa-mobile-
 * and-push.md §4.2):
 *
 * - `registerType: 'prompt'` means the new SW installs but stays "waiting".
 *   Nothing swaps until the user hits the reload banner. That preserves in-
 *   flight composer drafts, scroll position, and open approval prompts.
 * - We poll `update()` every 30 minutes so long-open tabs eventually see
 *   the new version instead of running on a stale bundle forever.
 * - We register only in production builds. In `vite dev` the plugin is
 *   disabled, so `virtual:pwa-register` synchronously returns a no-op —
 *   but we still guard on `import.meta.env.PROD` to be explicit.
 */

export type PwaLifecycleHandlers = {
  onNeedRefresh: () => void
  onOfflineReady: () => void
  onRegistered?: (registration: ServiceWorkerRegistration | undefined) => void
  onRegisterError?: (error: unknown) => void
}

export type PwaController = {
  /** Send SKIP_WAITING to the waiting worker and reload once it activates. */
  applyUpdate: () => Promise<void>
  /** Manually trigger an update check. */
  checkForUpdate: () => Promise<void>
}

const NOOP_CONTROLLER: PwaController = {
  applyUpdate: async () => {},
  checkForUpdate: async () => {},
}

const UPDATE_POLL_INTERVAL_MS = 30 * 60 * 1000

export function initPwa(handlers: PwaLifecycleHandlers): PwaController {
  if (typeof window === 'undefined') return NOOP_CONTROLLER
  if (!('serviceWorker' in navigator)) return NOOP_CONTROLLER
  // In dev the vite-plugin-pwa virtual module is intentionally a no-op, but
  // the import still resolves. Guard on PROD anyway so we never register a
  // worker against a Vite dev server (which would break HMR).
  if (!import.meta.env.PROD) return NOOP_CONTROLLER

  let updateSW: ((reloadPage?: boolean) => Promise<void>) | undefined
  let pollTimer: ReturnType<typeof setInterval> | undefined

  const load = async (): Promise<void> => {
    try {
      // The virtual module is generated by vite-plugin-pwa at build time.
      // Dynamic import so tests can execute this file without the plugin.
      const mod = await import(/* @vite-ignore */ 'virtual:pwa-register')
      updateSW = mod.registerSW({
        immediate: true,
        onNeedRefresh: () => handlers.onNeedRefresh(),
        onOfflineReady: () => handlers.onOfflineReady(),
        onRegisteredSW: (_url: string, registration: ServiceWorkerRegistration | undefined) => {
          handlers.onRegistered?.(registration)
          if (registration) {
            pollTimer = setInterval(() => {
              // Ignore rejections: a transient network failure just means we
              // retry in 30 minutes.
              registration.update().catch(() => {})
            }, UPDATE_POLL_INTERVAL_MS)
          }
        },
        onRegisterError: (error: unknown) => handlers.onRegisterError?.(error),
      })
    } catch (error) {
      handlers.onRegisterError?.(error)
    }
  }

  void load()

  // The SW notificationclick handler posts { type: 'PUSH_NAVIGATE', url }
  // when the user taps a notification and an existing tab is focused
  // instead of opening a new window. Route the deep-link into the app's
  // hash router so the same code path handles both entry modes.
  const onSwMessage = (event: MessageEvent): void => {
    const data = event.data as { type?: string; url?: string } | null
    if (!data || data.type !== 'PUSH_NAVIGATE' || typeof data.url !== 'string') return
    try {
      const url = new URL(data.url, window.location.origin)
      if (url.hash) {
        window.location.hash = url.hash
      } else if (url.pathname && url.pathname !== window.location.pathname) {
        window.location.href = url.toString()
      }
    } catch {
      // Malformed URL from a stale SW — ignore.
    }
  }
  navigator.serviceWorker.addEventListener('message', onSwMessage)

  window.addEventListener('beforeunload', () => {
    if (pollTimer) clearInterval(pollTimer)
    navigator.serviceWorker.removeEventListener('message', onSwMessage)
  })

  return {
    applyUpdate: async () => {
      if (updateSW) await updateSW(true)
    },
    checkForUpdate: async () => {
      const registration = await navigator.serviceWorker.getRegistration()
      if (registration) await registration.update()
    },
  }
}

/**
 * Standalone-mode detection. Used to hide "add to home screen" hints once
 * the app is already installed, and to gate iOS-only push flows (iOS 16.4+
 * only allows PushManager.subscribe when display-mode === 'standalone').
 */
export function isStandalone(): boolean {
  if (typeof window === 'undefined') return false
  if (window.matchMedia?.('(display-mode: standalone)').matches) return true
  // Legacy iOS Safari — property is non-standard but still present in iOS 17.
  const nav = navigator as unknown as { standalone?: boolean }
  return nav.standalone === true
}
